language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^[0-9]+[.][0-9]+$ ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

script:
  - php -dmemory-limit=2G /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/composer update --no-interaction
  - ./vendor/phpunit/phpunit/phpunit -v
