language: php
php:
  - 5.6
  - 5.5
  - hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^php ]]; then phpenv config-rm xdebug.ini; fi
  - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer.phar self-update
  - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer.phar update --memory=1G --no-interaction --prefer-dist

script:
  - ./vendor/phpunit/phpunit/phpunit -v
