language: php
php:
  - 5.6
  - 5.5
  - hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^[0-9]+[.][0-9]+$ ]]; then phpenv config-rm xdebug.ini; fi

script:
  - ./vendor/phpunit/phpunit/phpunit -v
